# Generated by Django 4.0.3 on 2022-05-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('education_name', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'verbose_name': 'Education_code',
                'unique_together': {('education_id', 'education_name')},
            },
        ),
    ]
