# Generated by Django 4.0.3 on 2022-05-19 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0011_rename_race_total_incomestatetotal_income_total'),
        ('realestate_education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_estimate_value', models.FloatField(blank=True, null=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='county_est_ed', to='realestate_app.county')),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_estimate', to='realestate_education.education')),
            ],
            options={
                'verbose_name': 'Education_Estimate',
                'unique_together': {('education', 'county')},
            },
        ),
        migrations.CreateModel(
            name='EducationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_error_value', models.FloatField(blank=True, null=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='county_err_ed', to='realestate_app.county')),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_error', to='realestate_education.education')),
            ],
            options={
                'verbose_name': 'Education_Error',
                'unique_together': {('education', 'county')},
            },
        ),
    ]
