# Generated by Django 4.0.3 on 2022-05-23 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0012_county_education_total_county_poverty_total'),
        ('realestate_education', '0002_educationestimate_educationerror'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationStateTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_total', models.FloatField(blank=True, null=True)),
                ('education_total', models.FloatField(blank=True, null=True)),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edu_idte', to='realestate_education.education')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_idte', to='realestate_app.state')),
            ],
            options={
                'verbose_name': 'Education_State_Total',
                'unique_together': {('state', 'education')},
            },
        ),
    ]
