# Generated by Django 4.0.3 on 2022-06-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenure',
            fields=[
                ('tenure_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('tenure_name', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'verbose_name': 'Tenure_code',
                'unique_together': {('tenure_id', 'tenure_name')},
            },
        ),
    ]
