# Generated by Django 4.0.3 on 2022-06-13 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0016_county_mobility_total'),
        ('realestate_tenure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenureEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenure_estimate_value', models.FloatField(blank=True, null=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='county_est_te', to='realestate_app.county')),
                ('tenure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenure_estimate', to='realestate_tenure.tenure')),
            ],
            options={
                'verbose_name': 'Tenure_Estimate',
                'unique_together': {('tenure', 'county')},
            },
        ),
        migrations.CreateModel(
            name='TenureError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenure_error_value', models.FloatField(blank=True, null=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='county_err_te', to='realestate_app.county')),
                ('tenure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenure_error', to='realestate_tenure.tenure')),
            ],
            options={
                'verbose_name': 'Tenure_Error',
                'unique_together': {('tenure', 'county')},
            },
        ),
    ]
