# Generated by Django 4.0.3 on 2022-06-14 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0017_county_tenure_total'),
        ('realestate_tenure', '0002_tenureestimate_tenureerror'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenureStateTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_total', models.FloatField(blank=True, null=True)),
                ('tenure_total', models.FloatField(blank=True, null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_idtte', to='realestate_app.state')),
                ('tenure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenure_idtte', to='realestate_tenure.tenure')),
            ],
            options={
                'verbose_name': 'tenure_State_Total',
                'unique_together': {('state', 'tenure')},
            },
        ),
    ]
