# Generated by Django 4.0.3 on 2022-05-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SexAge',
            fields=[
                ('sex_age_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('sex_age_name', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'verbose_name': 'Sex_Age_code',
                'unique_together': {('sex_age_id', 'sex_age_name')},
            },
        ),
    ]
