# Generated by Django 4.0.3 on 2022-05-27 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0012_county_education_total_county_poverty_total'),
        ('realestate_sex_age', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SexAgeEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_age_estimate_value', models.FloatField(blank=True, null=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='county_est_sa', to='realestate_app.county')),
                ('sex_age', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sex_age_estimate', to='realestate_sex_age.sexage')),
            ],
            options={
                'verbose_name': 'Sex_Age_Estimate',
                'unique_together': {('sex_age', 'county')},
            },
        ),
        migrations.CreateModel(
            name='SexAgeError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_age_error_value', models.FloatField(blank=True, null=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='county_err_sa', to='realestate_app.county')),
                ('sex_age', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sex_age_error', to='realestate_sex_age.sexage')),
            ],
            options={
                'verbose_name': 'Sex_Age_Error',
                'unique_together': {('sex_age', 'county')},
            },
        ),
    ]
