# Generated by Django 4.0.3 on 2022-05-30 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0013_county_sex_age_total'),
        ('realestate_sex_age', '0002_sexageestimate_sexageerror'),
    ]

    operations = [
        migrations.CreateModel(
            name='SexAgeStateTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_total', models.FloatField(blank=True, null=True)),
                ('sex_age_total', models.FloatField(blank=True, null=True)),
                ('sex_age', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sex_age_idtsa', to='realestate_sex_age.sexage')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_idtsa', to='realestate_app.state')),
            ],
            options={
                'verbose_name': 'Sex_Age_State_Total',
                'unique_together': {('state', 'sex_age')},
            },
        ),
    ]
