# Generated by Django 4.0.3 on 2022-06-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobility',
            fields=[
                ('mobility_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('mobility_name', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'verbose_name': 'Mobility_code',
                'unique_together': {('mobility_id', 'mobility_name')},
            },
        ),
    ]
