# Generated by Django 4.0.3 on 2022-06-06 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0015_county_occupancy_total'),
        ('realestate_mobility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilityEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobility_estimate_value', models.FloatField(blank=True, null=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='county_est_mob', to='realestate_app.county')),
                ('mobility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobility_estimate', to='realestate_mobility.mobility')),
            ],
            options={
                'verbose_name': 'Mobility_Estimate',
                'unique_together': {('mobility', 'county')},
            },
        ),
        migrations.CreateModel(
            name='MobilityError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobility_error_value', models.FloatField(blank=True, null=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='county_err_mob', to='realestate_app.county')),
                ('mobility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobility_error', to='realestate_mobility.mobility')),
            ],
            options={
                'verbose_name': 'Mobility_Error',
                'unique_together': {('mobility', 'county')},
            },
        ),
    ]
