# Generated by Django 4.0.3 on 2022-06-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0016_county_mobility_total'),
        ('realestate_mobility', '0002_mobilityestimate_mobilityerror'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilityStateTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_total', models.FloatField(blank=True, null=True)),
                ('mobility_total', models.FloatField(blank=True, null=True)),
                ('mobility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobility_idtmob', to='realestate_mobility.mobility')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_idtmob', to='realestate_app.state')),
            ],
            options={
                'verbose_name': 'Mobility_State_Total',
                'unique_together': {('state', 'mobility')},
            },
        ),
    ]
