# Generated by Django 4.0.3 on 2022-05-20 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0011_rename_race_total_incomestatetotal_income_total'),
        ('realestate_poverty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PovertyEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poverty_estimate_value', models.FloatField(blank=True, null=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='county_est_pov', to='realestate_app.county')),
                ('poverty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poverty_estimate', to='realestate_poverty.poverty')),
            ],
            options={
                'verbose_name': 'Poverty_estimate',
                'unique_together': {('poverty', 'county')},
            },
        ),
        migrations.CreateModel(
            name='PovertyError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poverty_error_value', models.FloatField(blank=True, null=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='county_err_pov', to='realestate_app.county')),
                ('poverty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poverty_error', to='realestate_poverty.poverty')),
            ],
            options={
                'verbose_name': 'Poverty_error',
                'unique_together': {('poverty', 'county')},
            },
        ),
    ]
