# Generated by Django 4.0.3 on 2022-05-23 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0012_county_education_total_county_poverty_total'),
        ('realestate_poverty', '0002_povertyestimate_povertyerror'),
    ]

    operations = [
        migrations.CreateModel(
            name='PovertyStateTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('povertytotal', models.FloatField(blank=True, null=True)),
                ('statetotal', models.FloatField(blank=True, null=True)),
                ('poverty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poverty_pst_id', to='realestate_poverty.poverty')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_pst_id', to='realestate_app.state')),
            ],
            options={
                'verbose_name': 'Poverty_State',
                'unique_together': {('poverty', 'state')},
            },
        ),
    ]
