# Generated by Django 4.0.3 on 2022-05-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_poverty', '0003_povertystatetotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='povertystatetotal',
            old_name='povertytotal',
            new_name='poverty_total',
        ),
        migrations.RenameField(
            model_name='povertystatetotal',
            old_name='statetotal',
            new_name='state_total',
        ),
    ]
