# Generated by Django 4.0.3 on 2022-04-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('race_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('race_name', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
    ]
