# Generated by Django 4.0.3 on 2022-04-14 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('state_name', models.CharField(blank=True, max_length=225, null=True)),
                ('state_ref_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'State',
            },
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'verbose_name': 'Race_code'},
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('county_name', models.CharField(blank=True, max_length=225, null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='realestate_app.state')),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
            },
        ),
    ]
