# Generated by Django 4.0.3 on 2022-04-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0003_raceestimate_raceerror'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='raceerror',
            unique_together={('race', 'county')},
        ),
        migrations.AlterUniqueTogether(
            name='raceestimate',
            unique_together={('race', 'county')},
        ),
    ]
