# Generated by Django 4.0.3 on 2022-04-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0004_alter_raceerror_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='race_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
