# Generated by Django 4.0.3 on 2022-04-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0005_county_race_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('income_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('income_name', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'verbose_name': 'Income_code',
            },
        ),
    ]
