# Generated by Django 4.0.3 on 2022-05-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0008_racestatetotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='income_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
