# Generated by Django 4.0.3 on 2022-05-13 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0009_county_income_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeStateTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_total', models.FloatField(blank=True, null=True)),
                ('race_total', models.FloatField(blank=True, null=True)),
                ('income', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_idti', to='realestate_app.income')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_idti', to='realestate_app.state')),
            ],
            options={
                'verbose_name': 'Income_State_Total',
                'unique_together': {('state', 'income')},
            },
        ),
    ]
