# Generated by Django 4.0.3 on 2022-05-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0010_incomestatetotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomestatetotal',
            old_name='race_total',
            new_name='income_total',
        ),
    ]
