# Generated by Django 4.0.3 on 2022-05-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0011_rename_race_total_incomestatetotal_income_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='education_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='poverty_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
