# Generated by Django 4.0.3 on 2022-05-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0012_county_education_total_county_poverty_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='sex_age_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
