# Generated by Django 4.0.3 on 2022-05-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0013_county_sex_age_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='house_price_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
