# Generated by Django 4.0.3 on 2022-06-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0014_county_house_price_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='occupancy_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
