# Generated by Django 4.0.3 on 2022-06-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0015_county_occupancy_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='mobility_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
