# Generated by Django 4.0.3 on 2022-06-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0016_county_mobility_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='tenure_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
