# Generated by Django 4.0.3 on 2022-06-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('occupancy_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('occupancy_name', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'verbose_name': 'Occupancy_code',
                'unique_together': {('occupancy_id', 'occupancy_name')},
            },
        ),
    ]
