# Generated by Django 4.0.3 on 2022-05-31 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0013_county_sex_age_total'),
        ('realestate_house_price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePriceEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_price_estimate_value', models.FloatField(blank=True, null=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='county_est_hp', to='realestate_app.county')),
                ('house_price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_price_estimate', to='realestate_house_price.houseprice')),
            ],
            options={
                'verbose_name': 'House_Price_Estimate',
                'unique_together': {('house_price', 'county')},
            },
        ),
        migrations.CreateModel(
            name='HousePriceError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_price_error_value', models.FloatField(blank=True, null=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='county_err_hp', to='realestate_app.county')),
                ('house_price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_price_error', to='realestate_house_price.houseprice')),
            ],
            options={
                'verbose_name': 'House_Price_Error',
                'unique_together': {('house_price', 'county')},
            },
        ),
    ]
