# Generated by Django 4.0.3 on 2022-05-31 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0014_county_house_price_total'),
        ('realestate_house_price', '0002_housepriceestimate_housepriceerror'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePriceStateTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_total', models.FloatField(blank=True, null=True)),
                ('house_price_total', models.FloatField(blank=True, null=True)),
                ('house_price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hp_idthp', to='realestate_house_price.houseprice')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_idthp', to='realestate_app.state')),
            ],
            options={
                'verbose_name': 'House_Price_State_Total',
                'unique_together': {('state', 'house_price')},
            },
        ),
    ]
